#!/bin/bash

while true
do

# Logo

echo "============================================================"
curl -s https://raw.githubusercontent.com/AlekseyMoskalev1/script/main/Noders.sh | bash
echo "============================================================"

# Menu

PS3='Select an action: '
options=(
"Update Aptos"
"Update peer"
"Log Node"
"Exit")
select opt in "${options[@]}"
do
case $opt in

# Docker

"Update Aptos")
echo "============================================================"
echo "Update start"
echo "============================================================"
cd $HOME/aptos
sudo docker compose down -v
sudo docker pull aptoslab/validator:devnet
sudo docker pull aptoslab/tools:devnet

sudo docker run --rm --name aptos_tools -d -i aptoslab/tools:devnet
sudo docker cp $HOME/aptos/identity/private-key.txt aptos_tools:/root
sudo docker exec -it aptos_tools aptos-operational-tool extract-peer-from-file --encoding hex --key-file $HOME/private-key.txt --output-file $HOME/peer-info.yaml
sudo docker exec -it aptos_tools cat $HOME/peer-info.yaml > $HOME/aptos/identity/peer-info.yaml
sudo docker stop aptos_tools

PEER_ID=$(sed -n 2p $HOME/aptos/identity/peer-info.yaml | sed 's/..$//')
sed -i -e "s/peer_id:.*/peer_id: \"$PEER_ID\"/" $HOME/aptos/public_full_node.yaml
rm $HOME/aptos/genesis.blob
wget -P $HOME/aptos https://devnet.aptoslabs.com/genesis.blob
rm $HOME/aptos/waypoint.txt
wget -P $HOME/aptos https://devnet.aptoslabs.com/waypoint.txt

sed -i.bak 's/\(from_config: \).*/\1"'$(cat $HOME/aptos/waypoint.txt)'"/g' $HOME/aptos/public_full_node.yaml
sudo docker compose up -d

break
;;

"Update peer")
echo "============================================================"
echo "Update start"
echo "============================================================"
sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64  &> /dev/null
sudo chmod a+x /usr/local/bin/yq
cd $HOME/aptos

wget -O seeds.yaml https://raw.githubusercontent.com/razumv/helpers/main/aptos/seeds.yaml

/usr/local/bin/yq ea -i 'select(fileIndex==0).full_node_networks[0].seeds = select(fileIndex==1).seeds | select(fileIndex==0)' $HOME/aptos/public_full_node.yaml $HOME/aptos/seeds.yaml
rm $HOME/aptos/seeds.yaml

sudo docker compose restart

break
;;

"Log Node")
docker logs -f aptos-fullnode-1 --tail 5000
break
;;

"Exit")
exit
;;
*) echo "invalid option $REPLY";;
esac
done
done
