#!/bin/bash

while true
do

echo "============================================================"
curl -s https://raw.githubusercontent.com/AlekseyMoskalev1/script/main/Noders.sh | bash
echo "============================================================"


PS3='Select an action: '
options=(
"Update Gear Node"
"Log Node"
"Exit")
select opt in "${options[@]}"
               do
                   case $opt in
                   
"Update Gear Node")
               echo "============================================================"
               echo "Update has begun"
               echo "============================================================"
sudo systemctl stop gear-node               
cd $HOME
rm gear-node

wget https://builds.gear.rs/gear-nightly-linux-x86_64.tar.xz && \
tar xvf gear-nightly-linux-x86_64.tar.xz && \
rm gear-nightly-linux-x86_64.tar.xz && \
chmod +x gear-node

sudo apt install -y clang build-essential

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env

rustup toolchain add nightly
rustup target add wasm32-unknown-unknown --toolchain nightly

git clone https://github.com/gear-tech/gear.git
cd gear

cargo build -p gear-node --release

sudo systemctl restart gear-node

               echo "============================================================"
               echo "Update is ready!"
               echo "============================================================"
break
;;

"Log Node")

sudo journalctl -n 100 -f -u gear-node

break
;;

"Exit")
exit
;;

*) echo "invalid option $REPLY";;
esac
done
done
