#!/bin/bash

while true
do

#Logo

echo "============================================================"
curl -s https://raw.githubusercontent.com/AlekseyMoskalev1/script/main/Noders.sh | bash
echo "============================================================"

#Menu

PS3='Select an action: '
options=(
"Install Docker"
"Update ATP"
"Setup Masa"
"Remove Masa"
"Exit")
select opt in "${options[@]}"
do
case $opt in

#Docker

"Install Docker")
echo "============================================================"
echo "Docker installation started"
echo "============================================================"
sudo apt-get install curl gnupg apt-transport-https ca-certificates \
lsb-release -y && curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
| sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
echo "deb [arch=$(dpkg --print-architecture) \
signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
| sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
sudo apt-get update && \
sudo apt-get install docker-ce docker-ce-cli containerd.io -y
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
sudo chmod +x /usr/local/bin/docker-compose && docker-compose --version
echo "============================================================"
echo "Docker installed"
echo "============================================================"
break
;;

# ATP

"Update ATP")
echo "============================================================"
echo "ATP update started"
echo "============================================================"
sudo apt update && sudo apt upgrade -y
echo "============================================================"
echo "ATP updated"
echo "============================================================"
break
;;

#Instal

"Setup Masa")
echo "============================================================"
echo "Node installation started"
echo "============================================================"
git clone https://github.com/masa-finance/masa-node-v1.0
cd masa-node-v1.0
PRIVATE_CONFIG=ignore docker-compose up -d
echo "============================================================"
echo "Checking the logs"
echo "============================================================"
docker logs masa-node-v10_masa-node_1 -f --tail 10
echo "============================================================"
echo "If there are no errors in the logs, congratulations, the node is
installed. If you have any doubts - send screenshots to our support chat"
echo "============================================================"
break
;;

#Remove

"Remove Masa")
docker stop  masa-node-v10_masa-node_1
docker rm  masa-node-v10_masa-node_1
rm -r masa-node-v1.0
echo "============================================================"
echo "Masa removed"
echo "============================================================"
break
;;

#Exit

"Exit")
exit
            ;;
*) echo "invalid option $REPLY";;
esac
done
done
