#!/bin/bash
echo "============================================================================="
curl -s https://raw.githubusercontent.com/AlekseyMoskalev1/script/main/Noders.sh | bash
echo "============================================================================="
PS3='Выберите действие: '
options=("Установить Docker" "Обновить пакетный менеджер apt" "Установить Masa" "Выход")
select opt in "${options[@]}"
do
    case $opt in
        "Установить Docker")
            echo "Установка Docker началась"
            ;;
        "Обновить пакетный менеджер apt")
            echo "Обновление apt началось"
            ;;
        "Установить Masa")
            echo "Установка началась"
            ;;
        "Выход")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
