#!/bin/bash

echo -e "                                     ;                                                                                                                       "
echo -e "                                :       ED.                                                :;;;;                                                             "  
echo -e "    DKKKD  L.                  t#,      E#Wi                  ,;                        .  tKK##:                     ,;                                     "
echo -e "    K#f;,  EW:        ,ft     ;##W.     E###G.              f#i   j.                   ;W     ##:                   f#i                                      "
echo -e "    K#i    E##;       t#E    :#L:WE     E#fD#W;           .E#t    EW,                 f#E     ##:  GEEEEEEEL      .E#t               ..            ..       :"
echo -e "    K#i    E###t      t#E   .KG  ,#D    E#t t##L         i#W,     E##j              .E#f      ##:  ,;;L#K;;.     i#W,               ;W,           ,W,     .Et"
echo -e "    K#i    E#fE#f     t#E   EE    ;#f   E#t  .E#K,      L#D.      E###D.           iWW;       ##:     t#E       L#D.               j##,          t##,    ,W#t"
echo -e "    K#i    E#t D#G    t#E  f#.     t#i  E#t    j##f   :K#Wfff;    E#jG#W;         L##Lffi     ##:     t#E     :K#Wfff;            G###,         L###,   j###t"
echo -e "   K#i    E#t  f#E.  t#E  :#G     GK   E#t    :E#K:  i##WLLLLt   E#t t##f       tLLG##L      ##:     t#E     i##WLLLLt         :E####,       .E#j##,  G#fE#t "
echo -e "    K#i    E#t   t#K: t#E   ;#L   LW.   E#t   t##L     .E#L       E#t  :K#E:       ,W#i       ##:     t#E      .E#L            ;W#DG##,      ;WW; ##,:K#i E#t"
echo -e "    K#i    E#t    ;#W,t#E    t#f f#:    E#t .D#W;        f#E:     E#KDDDD###i     j#E.        ##:     t#E        f#E:         j###DW##,     j#E.  ##f#W,  E#t"
echo -e "    K#i    E#t     :K#D#E     f#D#;     E#tiW#G.          ,WW;    E#f,t#Wi,,,   .D#j          ##:     t#E         ,WW;       G##i,,G##,   .D#L    ###K:   E#t"
echo -e "    K#Lti  E#t      .E##E      G#t      E#K##i             .D#;   E#t  ;#W:    ,WK,        tKK##:     t#E          .D#;    :K#K:   L##,  :K#t     ##D.    E#t"
echo -e "    fGGGf  ..         G#E       t       E##D.                tt   DWi   ,KK:   EG.         :;;;;       fE            tt   ;##D.    L##,  ...      #G      .. "
echo -e "                       fE               E#t                                    ,                        :                 ,,,      .,,            j          "
