#!/bin/bash

while true
do

# Logo

echo "============================================================"
curl -s https://raw.githubusercontent.com/AlekseyMoskalev1/script/main/Noders.sh | bash
echo "============================================================"

# Menu

PS3='Select an action: '
options=(
"Preparing to install a node"
"Install Node"
"Exit")
select opt in "${options[@]}"
do
case $opt in

# Preparing

"Preparing to install a node")
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install tar curl ufw jq -y
wget https://golang.org/dl/go1.16.7.linux-amd64.tar.gz; \
rm -rv /usr/local/go; \
tar -C /usr/local -xzf go1.16.7.linux-amd64.tar.gz && \
rm -v go1.16.7.linux-amd64.tar.gz && \
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile && \
source ~/.bash_profile && \
go version
break
;;

# Install

"Install Node")
mkdir $HOME/stratos; cd $HOME/stratos; \
wget https://github.com/stratosnet/stratos-chain/releases/download/v0.5.0/stchaincli && \
wget https://github.com/stratosnet/stratos-chain/releases/download/v0.5.0/stchaind
chmod +x stchaincli stchaind && \
ln -s $HOME/stratos/stchaincli /usr/bin/ && \
ln -s $HOME/stratos/stchaind /usr/bin/
echo "============================================================"
echo "Enter your Node name: "
echo "============================================================"
read nickname
echo "export NICKNAME="$nickname"" >> ~/.bash_profile
source ~/.bash_profile
stchaind init $nickname
rm -vf $HOME/.stchaind/config/genesis* $HOME/.stchaind/config/config.toml && \
wget -P $HOME/.stchaind/config/ https://raw.githubusercontent.com/stratosnet/stratos-chain-testnet/main/genesis.json && \
wget -P $HOME/.stchaind/config/ https://raw.githubusercontent.com/stratosnet/stratos-chain-testnet/main/config.toml
sed -i "s/mynode/"$NICKNAME"/g" $HOME/.stchaind/config/config.toml

sudo tee <<EOF >/dev/null /etc/systemd/system/stratosd.service
[Unit]
Description=Stratos Node
After=network-online.target
[Service]
User=$USER
ExecStart=/usr/bin/stchaind start
Restart=always
RestartSec=10
LimitNOFILE=10000
[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload && \
sudo systemctl enable stratosd && sudo systemctl restart stratosd
echo "============================================================"
echo ""Checking the logs"
echo "============================================================"
sudo journalctl -u stratosd -f
break
;;

#Exit

"Exit")
exit
;;
*) echo "invalid option $REPLY";;
esac
done
done
